"""
Export SQLite budget data to static JSON files consumed by the SvelteKit frontend.

Usage:
    python pipeline/export_json.py [--db PATH] [--out DIR]

Defaults:
    --db   data/review/budget.sqlite
    --out  frontend/src/lib/data
"""

import argparse
import json
import os
import sqlite3
from pathlib import Path


def export(db_path: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row

    # expenditure_areas.json
    areas = [dict(r) for r in con.execute("SELECT id, name FROM expenditure_areas ORDER BY id")]
    write_json(out_dir / "expenditure_areas.json", areas)

    # available_years.json
    years = [
        r["budget_year"]
        for r in con.execute("SELECT DISTINCT budget_year FROM budget_values ORDER BY budget_year")
    ]
    write_json(out_dir / "available_years.json", years)

    # budget_{year}.json — one file per year
    for year in years:
        government = [
            {"area_id": r["area_id"], "amount_ksek": r["amount_ksek"]}
            for r in con.execute(
                "SELECT area_id, amount_ksek FROM budget_values WHERE budget_year = ? ORDER BY area_id",
                (year,),
            )
        ]

        parties: dict[str, list] = {}
        for row in con.execute(
            "SELECT party, area_id, delta_ksek FROM counter_deviations WHERE budget_year = ? ORDER BY party, area_id",
            (year,),
        ):
            parties.setdefault(row["party"], []).append(
                {"area_id": row["area_id"], "delta_ksek": row["delta_ksek"]}
            )

        write_json(out_dir / f"budget_{year}.json", {"government": government, "parties": parties})

    # index.ts — typed re-export map so the frontend doesn't hardcode year imports
    ts_lines = [
        "// Auto-generated by pipeline/export_json.py — do not edit manually",
        "",
    ]
    for year in years:
        ts_lines.append(f"import budget{year} from './budget_{year}.json';")
    ts_lines += [
        "",
        "export interface AreaValue { area_id: number; amount_ksek: number | null }",
        "export interface AreaDelta { area_id: number; delta_ksek: number | null }",
        "export interface BudgetData {",
        "  government: AreaValue[];",
        "  parties: Record<string, AreaDelta[]>;",
        "}",
        "",
        "export const budgetByYear: Record<number, BudgetData> = {",
    ]
    for year in years:
        ts_lines.append(f"  {year}: budget{year} as BudgetData,")
    ts_lines += ["};", ""]

    (out_dir / "index.ts").write_text("\n".join(ts_lines))
    print(f"Written index.ts with years: {years}")

    con.close()
    print(f"Export complete → {out_dir}")


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2))
    print(f"  {path.name}")


if __name__ == "__main__":
    repo_root = Path(__file__).parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", default=str(repo_root / "data/review/budget.sqlite"))
    parser.add_argument("--out", default=str(repo_root / "frontend/src/lib/data"))
    args = parser.parse_args()
    export(Path(args.db), Path(args.out))
